# Generated by Django 5.2.5 on 2025-09-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_editora_livro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autores',
            new_name='Autor',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='biografia',
            new_name='biogra',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='data_nascimento',
            new_name='data_nasc',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='nacionalidade',
            new_name='nacion',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='ano_publicacao',
            new_name='ano',
        ),
        migrations.AlterField(
            model_name='livro',
            name='dimensoes',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='livro',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
