# Generated by Django 5.2.4 on 2025-08-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('nacionalidade', models.CharField(blank=True, max_length=30, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
